module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    styled: true,
    themes: [
      'light',
      'dark',
      'corporate',
      'garden',
      'forest',
      'lofi',
      'pastel',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'night',
      'coffee',
      'winter',
    ],
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: '',
    darkTheme: 'business',
  },
};
